/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.26.0-363-g3e64fec9f (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.26.0-363-g3e64fec9f"
#endif
#define SDL_REVISION_NUMBER 0
